### ISSUE TITLE
ERROR: esbench.client:u'match_description_facet_date_histogram

### ISSUE THREAD

**Issue by chaitanyaenr** [mkocikowski/esbench#77]
I followed the procedure given in the docs, I am getting the following error:

ERROR:esbench.client:u'match_description_facet_date_histogram'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/esbench/client.py", line 174, in main
    benchmark.run(batches)
  File "/usr/local/lib/python2.7/dist-packages/esbench/bench.py", line 370, in run
    self.observe()
  File "/usr/local/lib/python2.7/dist-packages/esbench/bench.py", line 329, in observe
    observation.record()
  File "/usr/local/lib/python2.7/dist-packages/esbench/bench.py", line 278, in record
    'stats': self._stats(),
  File "/usr/local/lib/python2.7/dist-packages/esbench/bench.py", line 222, in _stats
    stats['search']['groups'][query.name]['client_total'] = query.execution_count
KeyError: u'match_description_facet_date_histogram'

**Comment by minhdanh** [comment]
Confirm that I'm having the same issue

**Comment by chaitanyaenr** [comment]
@minhdanh I removed the "match_description_facet_date_histogram": {
            "facets": {
                "date_published": {
                    "date_histogram": {
                        "field" : "dates.date_published",
                        "interval" : "month"
                    }
                }
            }, 
            "fields": [
                "description"
            ], 
            "from": 0, 
            "query": {
                "match": {
                    "description": "computing V%(variable)s device portable"
                }
            }, 
            "size": 10
        }, 

from config.json and used the fork of alanbbr. It's working.

**Comment by minhdanh** [comment]
Thank you @chaitanyaenr
