### ISSUE TITLE
ERROR:esbench.client:'_all'

### ISSUE THREAD

**Issue by snanduriterra** [mkocikowski/esbench#78]
Hi I have followed the document and installed esbench, tried basic run on the localhost where ES is installed and I get the below error.

esbench run
INFO:esbench.data:downloading 'https://s3-us-west-1.amazonaws.com/esbench/appl_2005_aa.gz' to '/tmp/appl_2005_aa.gz'...
INFO:esbench.data:done downloading https://s3-us-west-1.amazonaws.com/esbench/appl_2005_aa.gz, time: 0.64s
INFO:esbench.bench:loaded 6 lines into index 'esbench_test', size: 120968 (0.00MB)
INFO:esbench.bench:beginning observation no: 1, 2017-02-18T01:29:05Z
INFO:esbench.bench:ran query 'match_description_facet_date_histogram' 100 times in 0.10s
INFO:esbench.bench:ran query 'match_description_sorted_abstract' 100 times in 0.08s
INFO:esbench.bench:ran query 'match_description' 100 times in 0.07s
INFO:esbench.bench:finished observation no: 1, id: 9b6e57bd, time: 0.245
ERROR:esbench.client:'_all'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/esbench/client.py", line 174, in main
    benchmark.run(batches)
  File "/usr/local/lib/python2.7/dist-packages/esbench/bench.py", line 370, in run
    self.observe()
  File "/usr/local/lib/python2.7/dist-packages/esbench/bench.py", line 329, in observe
    observation.record()
  File "/usr/local/lib/python2.7/dist-packages/esbench/bench.py", line 278, in record
    'stats': self._stats(),
  File "/usr/local/lib/python2.7/dist-packages/esbench/bench.py", line 210, in _stats
    stats = json.loads(resp.data)['_all']['indices'][esbench.TEST_INDEX_NAME]['primaries']
KeyError: '_all'

**Comment by wbypai** [comment]
Confirm that I'm having the same issue
